### ISSUE TITLE
failure on startup in termbox on debian buster

### ISSUE THREAD

**Issue by grindhold** [erroneousboat/slack-term#119] opened 2018-03-12 16:24 UTC
got the following when trying to use slack-term on debian buster.

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/erroneousboat/slack-term/vendor/github.com/nsf/termbox-go.send_attr(0xc400000000)
	/home/grindhold/go/src/github.com/erroneousboat/slack-term/vendor/github.com/nsf/termbox-go/termbox.go:154 +0x369
github.com/erroneousboat/slack-term/vendor/github.com/nsf/termbox-go.send_clear(0xb19080, 0xc4201f7c10)
	/home/grindhold/go/src/github.com/erroneousboat/slack-term/vendor/github.com/nsf/termbox-go/termbox.go:240 +0x3d
github.com/erroneousboat/slack-term/vendor/github.com/nsf/termbox-go.Sync(0xb37028, 0x856720)
	/home/grindhold/go/src/github.com/erroneousboat/slack-term/vendor/github.com/nsf/termbox-go/api.go:451 +0x32
github.com/erroneousboat/slack-term/vendor/github.com/erroneousboat/termui.termSync()
	/home/grindhold/go/src/github.com/erroneousboat/slack-term/vendor/github.com/erroneousboat/termui/render.go:82 +0x32
github.com/erroneousboat/slack-term/vendor/github.com/erroneousboat/termui.TermHeight(0x856720)
	/home/grindhold/go/src/github.com/erroneousboat/slack-term/vendor/github.com/erroneousboat/termui/render.go:95 +0x20
github.com/erroneousboat/slack-term/components.CreateChannelsComponent(0x3, 0x0)
	/home/grindhold/go/src/github.com/erroneousboat/slack-term/components/channels.go:112 +0x85
github.com/erroneousboat/slack-term/views.CreateView(0xc42022c000, 0xc4200cfb20, 0x0)
	/home/grindhold/go/src/github.com/erroneousboat/slack-term/views/view.go:25 +0x56
github.com/erroneousboat/slack-term/context.CreateAppContext(0xc4201a0240, 0x1d, 0x89a300, 0xc4201f7f78, 0x4042ac, 0xc420094058)
	/home/grindhold/go/src/github.com/erroneousboat/slack-term/context/context.go:53 +0xae
main.main()
	/home/grindhold/_git_archive/slack-term/main.go:90 +0xf8

```

**Comment by erroneousboat** [comment] 2018-03-23 10:59
At the moment I have no idea where this problem originates or how it is triggered. It seems to be caused by  calling the termui function `termui.TermHeight()`, but I don't know if this is an issue with termui, termbox-go, the specific terminal that is used or slack-term itself.

**Comment by grindhold** [comment] 2018-03-23 11:38
i tried with gnome-terminal and sakura. both are based on libvte 2.91.
go version go1.10rc2 linux/amd64
in case you need any other data to reproduce, please reach out.

**Comment by zabuTNT** [comment] 2018-03-23 13:49
same error for me... but I'm on Arch not Debian.
I build it from master branch with make build

terminal urxvt
go version go1.9 linux/amd64
slack-term v0.3.2

The strange thing is that with the release binary the error not occour.

**Comment by erroneousboat** [comment] 2018-03-23 16:45
Thank you for the information, I'll try to get it to happen to me as well.

**Comment by erroneousboat** [comment] 2018-10-27 14:45
Closing this due to age.

**Closed by erroneousboat** 2018-10-27 14:45 UTC
Labels: bug
