### ISSUE TITLE
Theme and configuration issues

### ISSUE THREAD

**Issue by apas** [erroneousboat/slack-term#111] opened 2018-03-03 14:10 UTC
First off, this looks cool, congrats. My current terminal client is [terminal-slack](https://github.com/evanyeung/terminal-slack). I use it occasionally but it gets the job done. I'd love to move away from a Node implementation to a Go one. However, before I can further test in order to switch I want to highlight two issues:

1. Current theme and colors don't play well with a Solarized Light environment. Text and UI elements like line borders are almost completely non-readable. Perhaps you can ship two theme versions or fix this one. (For both `xterm-color` and `xterm-256color`.)
2. Most importantly: make `slack-term.json` a dotfile. I hate having random files lying around my home directory. All config files should be dotfiles. (At the very least, also look for a `.slack-term.json` with a fallback to `slack-term.json`.)

**Comment by erroneousboat** [comment] 2018-03-18 09:16
Duplicate of #79 and #118

**Closed by erroneousboat** 2018-03-18 09:16 UTC

**Comment by apas** [comment] 2018-03-18 16:29
@erroneousboat, is there an ETA on either issue?

**Comment by seanfuture** [comment] 2018-04-16 03:48
Thanks @apas ~ Now using https://github.com/brileb73/terminal-slack/tree/add-groups
