### ISSUE TITLE
Immediate crash on WLS

### ISSUE THREAD

**Issue by ocket8888** [erroneousboat/slack-term#135] opened 2018-04-06 22:14 UTC
Yo, it's me again. Same `uname` as before (can't paste for reasons I don't want to get into rn). Build is now successful, but running fails immediately with the error
``` 2018/04/06 16:12:40 invalid argument ```
My `slack-term.json` file is one line: contains only my slack api token. Built from fresh source, just pulled a couple of seconds ago.

EDIT: I don't know how/why all of that got pasted into the title. Also, here's my `uname` output:
```
Linux <hostname redacted> 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by erroneousboat** [comment] 2018-04-07 08:49
Duplicate of #113

**Closed by erroneousboat** 2018-04-07 08:49 UTC
