### ISSUE TITLE
Does not work with st terminal

### ISSUE THREAD

**Issue by iveqy** [erroneousboat/slack-term#94] opened 2018-03-02 07:01 UTC
When starting slack-term from the st terminal ( https://st.suckless.org/ ) the screen is showing garbage and the program is unusable.

This is tested on alpine linux (musl based linux distribution)

**Comment by Xide** [comment] 2018-03-02 15:31
Hi,

I have the same issue here with different terminals, here is my config

- OS: `Linux 4.15.3-2-ARCH #1 SMP PREEMPT Thu Feb 15 00:13:49 UTC 2018 x86_64 GNU/Linux`
- Install method: `go get`
- Terminals: `urxvt`, `guake`
- Configuration: Copy of the exemple in README, without other modification than the token.
Demo: https://asciinema.org/a/7cydS1SlkzAUBVZe5xLsJ9Ibr

It however seems to work with `xterm` and `termite`.

**Comment by erroneousboat** [comment] 2018-03-18 09:41
@iveqy is this the same issue as #98?

**Comment by erroneousboat** [comment] 2018-03-18 09:59
@Xide thank you for the work-around!

**Comment by iveqy** [comment] 2018-03-18 11:02
@erroneousboat possible, but not necessarily. They seem to have the same symptom, but that doesn't mean that it's the same issue.

**Comment by erroneousboat** [comment] 2018-04-14 16:12
Duplicate of #98

**Closed by erroneousboat** 2018-04-14 16:12 UTC
