### ISSUE TITLE
Slack-term does not handle terminal resizing

### ISSUE THREAD

**Issue by howardcochran** [erroneousboat/slack-term#78] opened 2018-01-26 03:45 UTC
When the terminal is resized, slack-term does not notice. When the terminal is made smaller than it was when it was launched, the result is that it is unusable until the terminal size is restored or the app is restarted.

I am using version 0.3.0 on Ubuntu 16.04, typically running in tmux.  This is the current stable version available as a snap package.

**Comment by erroneousboat** [comment] 2018-01-26 11:40
Duplicate of: https://github.com/erroneousboat/slack-term/issues/56

I'll look if anything has changed

**Closed** 2018-01-27 11:58 UTC
Labels: bug
