### ISSUE TITLE
No notifications on Ubuntu 18.04 wayland

### ISSUE THREAD

**Issue by luciusbob** [erroneousboat/slack-term#210] opened 2019-09-25 11:34 UTC
I love this little tool, so much less distracting.

However, what is really an issue is not receiving any notifications. 

In my config file I have set "notify": "all"

---

Version: 0.4.1 on Ubuntu 18.04 wayland
Installation method: snap

**Comment by erroneousboat** [comment] 2019-09-26 10:50
Do you either have `notify-send` or `kdialog` installed on your system?

**Comment by lubobde** [comment] 2019-09-26 10:59
yes, notify-send vers. 0.7.7. And it is active. I get messages by it.

**Comment by lubobde** [comment] 2019-09-26 12:19
I have just run more experiments. I get a beep from the terminal window, but no notification via notify-send. Notify-send itselff is ok, other software make use of it.

**Comment by erroneousboat** [comment] 2019-09-28 09:41
Ok, I'm not able to reproduce this. Considering you do get the terminal beep. It could either be 1. the config is not correctly setup (seems unlikely what with you already provided), 2. problem with `notify-send` 3. Something different I don't see at the moment.

You could do the following:
1. Execute the following command: `notify-send -i "" slack-term test`. slack-term sends this command to `notify-send`. Just to check if this works, I have the same version as you for `notify-send` so I expect this to work.
2. Build slack-term from the master branch, and see if the problem persists

**Comment by lubobde** [comment] 2019-09-28 14:04
Notify-send from the CLI works fine.
The binay and the build I created with go created notifactions now. But I am just getting this:

![image](https://user-images.githubusercontent.com/5446606/65817598-a27a0700-e209-11e9-9758-b10f877d5715.png)

Is  this as it is supposed to be?

**Comment by erroneousboat** [comment] 2019-09-29 08:07
Yes, that is how it is supposed to look. Showing of contents of a message is on another issue.

**Comment by lubobde** [comment] 2019-09-29 10:57
OK, so case solved. Thank you very much for being so responsive.

**Comment by erroneousboat** [comment] 2019-10-01 07:35
Ok cool! Closing the issue

**Closed by erroneousboat** 2019-10-01 07:35 UTC
