### ISSUE TITLE
websocket error

### ISSUE THREAD

**Issue by comtom** [erroneousboat/slack-term#154] opened 2018-07-02 17:20 UTC
A panic error raises suddenly. On one ocasion I was sending a url and on other I wasn't typing or anything.

Error detail:
```
panic: repeated read on failed websocket connection
goroutine 249 [running]:
github.com/erroneousboat/slack-term/vendor/github.com/gorilla/websocket.(*Conn).NextReader(0xc420453a40, 0xffffffffffffffff, 0x0, 0xc420061ec8, 0xc420061ec8, 0x410ef8)
	/home/jp/go/src/github.com/erroneousboat/slack-term/vendor/github.com/gorilla/websocket/conn.go:958 +0x35d
github.com/erroneousboat/slack-term/vendor/github.com/gorilla/websocket.(*Conn).ReadJSON(0xc420453a40, 0x81c1c0, 0xc420445b20, 0x8f9b20, 0xc42043ed20)
	/home/jp/go/src/github.com/erroneousboat/slack-term/vendor/github.com/gorilla/websocket/json.go:45 +0x2f
github.com/erroneousboat/slack-term/vendor/github.com/nlopes/slack.(*RTM).receiveIncomingEvent(0xc4201cbb80)
	/home/jp/go/src/github.com/erroneousboat/slack-term/vendor/github.com/nlopes/slack/websocket_managed_conn.go:288 +0xa1
github.com/erroneousboat/slack-term/vendor/github.com/nlopes/slack.(*RTM).handleIncomingEvents(0xc4201cbb80, 0xc4200e9140)
	/home/jp/go/src/github.com/erroneousboat/slack-term/vendor/github.com/nlopes/slack/websocket_managed_conn.go:223 +0x2d
created by github.com/erroneousboat/slack-term/vendor/github.com/nlopes/slack.`(*RTM).ManageConnection
	/home/jp/go/src/github.com/erroneousboat/slack-term/vendor/github.com/nlopes/slack/websocket_managed_conn.go:54 +0x24d
```

**Comment by oliverseal** [comment] 2018-07-14 17:34
From what I can tell slack-term doesn't gracefully try to reconnect currently. Definitely a nice feature request, though.

**Comment by erroneousboat** [comment] 2018-07-21 11:04
Duplicate of #158

**Closed by erroneousboat** 2018-07-21 11:04 UTC
