### ISSUE TITLE
xterm standard colors have poor usability

### ISSUE THREAD

**Issue by iveqy** [erroneousboat/slack-term#95] opened 2018-03-02 07:02 UTC
When starting slack-term from xterm that has the default colors, that is white background and black foreground, the colors of slack-term has such low contrast that it's almost impossible to use the program. When starting xterm with `xterm -fg white -bg black` slack-term works fine.

**Comment by erroneousboat** [comment] 2018-03-18 09:00
Duplicate of #86

**Closed by erroneousboat** 2018-03-18 09:00 UTC
