### ISSUE TITLE
Support Multiple Workspace

### ISSUE THREAD

**Issue by horida** [erroneousboat/slack-term#96] opened 2018-03-02 08:46 UTC
I miss the multiple workspace support, which is mostly why I don't switch immediately to slack-term.

Meanwhile I'll use the various instances workaround https://github.com/erroneousboat/slack-term#usage

Awesome work though!

**Comment by erroneousboat** [comment] 2018-03-18 09:00
Duplicate of #46

**Closed by erroneousboat** 2018-03-18 09:00 UTC
