### ISSUE TITLE
App crashes with unsupported block type error when selecting specific channels

### ISSUE THREAD

**Issue by punkdata** [erroneousboat/slack-term#212] opened 2019-10-07 17:37 UTC
Please read [CONTRIBUTING.md](https://github.com/erroneousboat/slack-term/blob/master/CONTRIBUTING.md)

---

Version: Master Oct7
Installation method: GO build locally

The application works great but there are 2 slack channels that crash the app with the following error `unsupported block type`.  I've run the app with `-debug` flag in order to get a more detailed trace of the error but the app crashes with the same `unsupported block type` error.

I assume there is some malformed content in those channels but I can't figure out what that could be.

Has anyone see or reported this behavior previously? I searched the issues for this project and haven't found anything similar to this.

**Comment by erroneousboat** [comment] 2019-10-08 12:12
Hi, I'll have a look if I can reproduce the issue

**Comment by erroneousboat** [comment] 2019-10-12 11:05
Seems to be related to: https://github.com/nlopes/slack/issues/579

**Comment by punkdata** [comment] 2019-10-12 13:29
So I've also seen similar behavior in the linux slack desktop app when going to the same channels. In that case both Slack Desktop and Slack-Term app both crashed when accessing the same two channels. Though I just updated the desktop app and it no longer crashes. They obviously fixed the desktop app

**Comment by punkdata** [comment] 2019-10-12 13:30
I accidentally closed this issue😯

**Comment by jsavin** [comment] 2019-10-28 19:06
Same error here, but it's happening when starting slack-term rather then on any specific channel (although perhaps the default channel is the specific channel that's causing the crash). My Slack workspace has a lot of integrations including some custom ones, and I wonder if that's a clue as to the cause.

**Comment by acaloiaro** [comment] 2019-11-04 23:54
This is indeed related to nlopes/slack#579; and I've proposed a patch there.

**Comment by yousafsyed-bg** [comment] 2019-12-17 14:26
Hellow is there a fix for this ? problem ?

**Comment by khanhtc1202** [comment] 2019-12-19 07:19
This error happened when searching text in search mode, not just on open a specific channel. Please let me know if I can assist.

**Comment by acaloiaro** [comment] 2019-12-27 13:51
@khanhtc1202 I have the fix merged over on my `slack-term` fork if you want to give it a go: https://github.com/acaloiaro/slack-term

**Comment by cdrrazan** [comment] 2019-12-30 05:56
Moved from old to new setup in my Ubuntu 18.04 and i am also facing the same problem when starting up the `slack-term`. 

Error Message
```
➜ slack-term
2019/12/30 11:39:03 unsupported block type
```

OS: Ubuntu 18.04

**Comment by erroneousboat** [comment] 2020-01-08 10:42
Updated master branch to use latest commit from nlopes/slack. Does that resolve the issue?

**Comment by acaloiaro** [comment] 2020-01-08 19:09
@erroneousboat I believe this is the fix https://github.com/nlopes/slack/pull/636

**Comment by james-relyea** [comment] 2020-01-09 16:15
> 
> 
> Updated master branch to use latest commit from nlopes/slack. Does that resolve the issue?

Can confirm this issue is resolved for me.

**Comment by cdrrazan** [comment] 2020-01-10 00:45
Fixes. :+1:

**Comment by erroneousboat** [comment] 2020-03-14 10:42
Closing this, seems to be resolved on master branch. If not I'll reopen.

**Closed by erroneousboat** 2020-03-14 10:42 UTC
Labels: bug

**Comment by vantaboard** [comment] 2022-06-10 19:24
I am experiencing this issue on my end.
