### ISSUE TITLE
Crashing when pasting text

### ISSUE THREAD

**Issue by imalexsq** [erroneousboat/slack-term#80] opened 2018-01-26 22:18 UTC
Tried pasting text:

-  in "Normal" mode throws `SEARCHpanic`

- in "INSERT" mode throws `nic: runtime error: slice bounds out of range─`

Using v0.3.0 with iTerm2 3.1.5 on OSX 10.13.2

**Comment by erroneousboat** [comment] 2018-01-27 08:57
Should be fixed in upcoming version `v0.3.1` https://github.com/erroneousboat/slack-term/commit/97c735f82885ac0ce2e7dbc3725e46f84ecd1235, otherwise this issue is a duplicate of https://github.com/erroneousboat/slack-term/issues/58

**Closed by erroneousboat** 2018-01-27 08:57 UTC
